server:
  port: 8844

spring:
  rabbitmq:
    addresses: 192.168.110.136
    port: 5672
    username: admin
    password: fanjie123
    virtual-host: /pay
    connection-timeout: 15000
    publisher-confirm-type: simple
    publisher-returns: true
    template.mandatory: true

    listener:
      simple:
        acknowledge-mode: manual  #签收模式-手工签收
        concurrency: 5 #监听限制 默认为5，最大为10
        max-concurrency: 10

