server:
  port: 8767

spring:
  application:
    name: mine-examination-server
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.110.162:3306/mini_examination?characterEncoding=utf-8&useSSL=false
    username: root
    password: fanjie

# 配置MyBatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置扫描通用枚举
  type-enums-package: cx.examination.enroll.common


##这里选择文件夹作为对外访问的目录，可以根据具体需求设置
upload-path: F:/image/
  ##表示所有的访问都经过静态资源路径
#spring.mvc.static-path-pattern=/**
#  spring.resources.static-locations=classpath\:/META-INF/resources/,classpath\:/resources/,classpath\:/static/,classpath\:/public/,file\:${web.upload-path}
#  classpath:/static/,classpath:/public/,file:${upload-path}
