server:
  port: 8833


spring:
  rabbitmq:
    addresses: 192.168.110.136
    port: 5672
    username: admin
    password: fanjie123
    virtual-host: /ymx
    connection-timeout: 15000
    publisher-confirm-type: simple
    publisher-returns: true
    template.mandatory: true
    listener:
      simple:
        # 设置消费端手动 ack
        acknowledge-mode: manual
        # 消费者最小数量 处理的线程数
        concurrency: 1
        # 消费之最大数量
        max-concurrency: 4
        # 在单个请求中处理的消息个数，他应该大于等于事务数量(unack的最大数量)
        prefetch: 1


