spring:
  application:
    name: ymdx-apollo-demo
#  profiles:
#    active: dev

project:
  version: 1.0.0

server:
  port: 8877
#
###appId
app:
  id: ymdx-apollo-demo-appid
# set apollo meta server address, adjust to actual address if necessary
apollo:
  ##指定集群，不加此配置默认为default
  #  cluster: default
  bootstrap:
    enabled: true
    ##需要拉取的配置,多个namespace用","连接
    namespaces: ymdx-apollo-demo
  ##缓存地址
  cacheDir: /opt/data/
  ##地址
  meta: http://192.168.110.126:8080

#app:
#  id: ymdx-real-time-bus-gateway-zuul
## set apollo meta server address, adjust to actual address if necessary
#apollo:
#  ##指定集群，不加此配置默认为default
#  #  cluster: default
#  bootstrap:
#    enabled: true
#    ##需要拉取的配置,多个namespace用","连接
#    namespaces: ymdx-bus-gateway-zuul.yml
#  ##缓存地址
#  cacheDir: /opt/data/